# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-04 09:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20161102_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxon',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Taxon'),
        ),
        migrations.AddField(
            model_name='taxon',
            name='position',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='taxonomy',
            name='position',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='taxon',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='taxon',
            name='image',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='taxon',
            name='meta_description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='taxon',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='taxon',
            name='meta_title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='taxon',
            name='permalink',
            field=models.URLField(blank=True, null=True),
        ),
    ]
