# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-04 09:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20161104_1212'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Brand',
        ),
    ]
