# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-06 09:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_delete_brand'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taxon',
            options={'verbose_name': 'taxon', 'verbose_name_plural': 'taxons'},
        ),
        migrations.AlterModelOptions(
            name='taxonomy',
            options={'verbose_name': 'taxonomy', 'verbose_name_plural': 'taxonomies'},
        ),
        migrations.AddField(
            model_name='taxon',
            name='visible',
            field=models.BooleanField(default=False, verbose_name='visible'),
        ),
        migrations.AddField(
            model_name='taxonomy',
            name='visible',
            field=models.BooleanField(default=False, verbose_name='visible'),
        ),
        migrations.AlterField(
            model_name='taxon',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='taxon',
            name='name',
            field=models.CharField(max_length=200, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='taxon',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Taxon', verbose_name='parent'),
        ),
        migrations.AlterField(
            model_name='taxon',
            name='permalink',
            field=models.URLField(blank=True, null=True, verbose_name='permalink'),
        ),
        migrations.AlterField(
            model_name='taxon',
            name='position',
            field=models.IntegerField(default=0, verbose_name='position'),
        ),
        migrations.AlterField(
            model_name='taxon',
            name='taxonomy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Taxonomy', verbose_name='taxonomy'),
        ),
        migrations.AlterField(
            model_name='taxonomy',
            name='name',
            field=models.CharField(max_length=200, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='taxonomy',
            name='position',
            field=models.IntegerField(default=0, verbose_name='position'),
        ),
    ]
